### ISSUE TITLE
System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by Chrisoldinho** [mann1x/BSManager#3]
2.0 Base Stations (latest firmware)
Using motherboard embedded bluetooth
Windows 10 x64 Nvidia 2080Ti 472.12
PiTool & SteamVR have recognised both base stations
PiTool V1.0.1.272
Headset FW V2.1.255.299

![BSManager](https://user-images.githubusercontent.com/24567397/135533653-e13b1107-9077-4464-b507-b79ce3f20a82.png)

BSManager_exceptions.log fills up very quickly, example:-

[30/09/2021 22:32:40] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at BSManager.Form1.AdvertisementWatcher_Received(BluetoothLEAdvertisementWatcher sender, BluetoothLEAdvertisementReceivedEventArgs args)
[30/09/2021 22:32:40] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at BSManager.Form1.AdvertisementWatcher_Received(BluetoothLEAdvertisementWatcher sender, BluetoothLEAdvertisementReceivedEventArgs args)
[30/09/2021 22:32:40] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at BSManager.Form1.AdvertisementWatcher_Received(BluetoothLEAdvertisementWatcher sender, BluetoothLEAdvertisementReceivedEventArgs args)
[30/09/2021 22:32:42] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at BSManager.Form1.AdvertisementWatcher_Received(BluetoothLEAdvertisementWatcher sender, BluetoothLEAdvertisementReceivedEventArgs args)
[30/09/2021 22:32:42] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at BSManager.Form1.AdvertisementWatcher_Received(BluetoothLEAdvertisementWatcher sender, BluetoothLEAdvertisementReceivedEventArgs args)
[30/09/2021 22:32:42] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at BSManager.Form1.AdvertisementWatcher_Received(BluetoothLEAdvertisementWatcher sender, BluetoothLEAdvertisementReceivedEventArgs args)
[30/09/2021 22:32:42] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at BSManager.Form1.AdvertisementWatcher_Received(BluetoothLEAdvertisementWatcher sender, BluetoothLEAdvertisementReceivedEventArgs args)

**Comment by mann1x** [comment]
Hey, never seen this error :)
Can you please post a full log?

**Comment by mann1x** [comment]
I see also "Discovered: 2/0", seems the Base Stations are not found in the SteamVR configuration file.
It's this one found in your steam install dir: config\lighthouse\lighthousedb.json
Can you post it here?

(use the code tag for both the log and steamvr config file)

**Comment by mann1x** [comment]
I've found the issue that was causing that loop.
The BS v2 should have a specific manufacturer data that reports the power state.
One of your BS does not answer with this data (LHB-C4CE4D8A).
It means the BS is faulty or the firmware corrupt.
Please use this debug pre-release version:

https://github.com/mann1x/BSManager/releases/tag/v2.3.1

Confirm it's working, you should see this message in the log:

[LHB-C4CE4D8A] Missing Manufacturer data! Could be faulty or have a corrupted firmware.

And don't forget please to post the SteamVR configuration file.

To fix the faulty BS you can try to leave it unplugged from power for several hours, overnight is a good choice.
If it's still not working either keep it as it is (doesn't seem causing troubles) or call Valve support.
They can either send you a firmware upgrade tool to force a re-flash or get it back in RMA.

**Comment by Chrisoldinho** [comment]
Hi, thanks so much for the speedy response whilst I was sleeping.

I have downloaded 2.3.1, it does not produce a **BSManager_exceptions.log** file anymore, only **BSManager.log** when I enable "Debug Log" from the application. See log below, and you are correct I see `[01/10/2021 08:58:47] [LHB-C4CE4D8A] Missing Manufacturer data! Could be faulty or have a corrupted firmware.` in the file...

[BSManager.log](https://github.com/mann1x/BSManager/files/7265304/BSManager.log)

contents of **lighthousedb.json**

`{
   "base_stations" : [],
   "known_objects" : [
      {
         "deviceClass" : "hmd",
         "serialNumber" : "LHR-EA9A4C57"
      }
   ],
   "known_universes" : [],
   "revision" : 2
}
`

**Comment by mann1x** [comment]
VivePro BS 2.0?
Gosh I had no idea they were existing...

That's why they don't answer that request, they are not Valve.

I'll have to prepare a new debug version for you to test.

For the LightHouse config I'll have to use the Pitool database.
I thought it was synced but probably not. They are not listed there if you only have a Pimax Headset.

**Comment by mann1x** [comment]
Can you please test this version and share the log here?

**Comment by Chrisoldinho** [comment]
> Can you please test this version and share the log here?
> 
> https://github.com/mann1x/BSManager/releases/tag/v.2.3.2

Do you want me to compile from source as no executable is included?

**Comment by mann1x** [comment]
Ooops 😄 
Now there's an executable

**Comment by Chrisoldinho** [comment]
Log from 2.3.2 attached.
[BSManager.log](https://github.com/mann1x/BSManager/files/7269428/BSManager.log)

For reference, slightly different designs on both.

**LHR-EA9A4C57** (now **LHB-E51869D0** for some reason?) on the left
**LHB-C4CE4D8A** on the right

![20211001_191846](https://user-images.githubusercontent.com/24567397/135670225-1d12d0ba-ca8d-4250-b0c1-85755b75203a.jpg)

![image](https://user-images.githubusercontent.com/24567397/135670565-3d4aa75d-b674-4c5e-8adc-bf3d8a4f6ec8.png)

**Comment by mann1x** [comment]
Thanks for the log.
Unfortunately the HTC version is inferior to the Valve one.
It doesn't export the power state.
At least, it's not defective.

It is now all working as expected?

**Comment by Chrisoldinho** [comment]
Yes I believe so, as it does not export the power state does this mean BSManager is unable to control wakeup and sleep commands for this device or am I misunderstanding your response?

**Comment by Chrisoldinho** [comment]
I just tested powering off the headset and both devices went into standby correctly.

For final reference, here is the log output from 2.3.2 showing initial wakeup and subsequent sleep commands.

[BSManager.log](https://github.com/mann1x/BSManager/files/7270125/BSManager.log)
